namespace ArcoroSamples.hh2
{
    public class Employee
    {
        //[Name("<NameOfHeaderInFile>"), Index(0)] - Index sets order of columns in file
        public int AcaCoverageCode { get; set; }
        public int AcaEmploymentStatus { get; set; }
        public int AcaPolicyOrigin { get; set; }
        public int AcaSafeHarborCode { get; set; }
        public double AcaSelfCoverageMonthlyPremiumAccount { get; set; }
        public string AddressCity { get; set; }
        public string AddressPostalCode { get; set; }
        public string AddressState { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Code { get; set; }
        public string Comments { get; set; }
        public string CustomCheckSortValue { get; set; }
        public string DefaultCertifiedClassId { get; set; }
        public string DefaultCertifiedClass { get; set; }
        public string DefaultDepartmentId { get; set; }
        public string DefaultDepartment { get; set; }
        public string DefaultEquipmentItemId { get; set; }
        public string DefaultEquipmentStandardCostCodeId { get; set; }
        public string DefaultJobId { get; set; }
        public string DefaultPayTypeId { get; set; }
        public string DefaultPayType { get; set; }
        public string DefaultPositionId { get; set; }
        public string DefaultStandardCostCodeId { get; set; }
        public string DefaultUnionClassId { get; set; }
        public string DefaultUnionClass { get; set; }
        public string DefaultUnionId { get; set; }
        public string DefaultUnion { get; set; }
        public string DefaultUnionLocalId { get; set; }
        public string DefaultUnionLocal { get; set; }
        public int EicStatus { get; set; }
        public string EmailAddress { get; set; }
        public string EmploymentStatusId { get; set; }
        public string EmploymentTypeId { get; set; }
        public int Ethnicity { get; set; }
        public int FilingStatus { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public int Gender { get; set; }
        public bool HasReceivedThirdPartySickPayForCurrentYear { get; set; }
        public bool HasRetirementPlan { get; set; }
        public string HireDate { get; set; }
        public string Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsArchived { get; set; }
        public bool IsDirectDepositEnabled { get; set; }
        public bool IsI9Verified { get; set; }
        public bool IsQualifiedForHireAct { get; set; }
        public bool IsServiceManagementTechnician { get; set; }
        public string LastName { get; set; }
        public string LastRaiseDate { get; set; }
        public string MainPhoneNumber { get; set; }
        public int MaritalStatus { get; set; }
        public double MaximumCheckAmount { get; set; }
        public string MiddleName { get; set; }
        public string Miscellaneous1 { get; set; }
        public string Miscellaneous2 { get; set; }
        public int MiscellaneousTaxCode { get; set; }
        public string Occupation { get; set; }
        public int PayFrequency { get; set; }
        public string PayGroupId { get; set; }
        public string PayGroup { get; set; }
        public string RehireDate { get; set; }
        public string ResidencyState { get; set; }
        public bool ShouldAutoBillEquipmentRevenue { get; set; }
        public bool ShouldExcludeFromCertifiedReport { get; set; }
        public bool ShouldUseW4Amounts { get; set; }
        public int SkillLevel { get; set; }
        public string StandardOccupationCode { get; set; }
        public int TaxExemptionCount { get; set; }
        public string TerminationDate { get; set; }
        public string Title { get; set; }
        public long Version { get; set; }
        public int W2FormAccess { get; set; }
        public double W4DeductionsAmount { get; set; }
        public double W4DependentsAmount { get; set; }
        public double W4ExtraWithholdingsAmount { get; set; }
        public bool W4HasSpecifiedTwoJobs { get; set; }
        public double W4OtherIncomeAmount { get; set; }
        public string W4SignatureDate { get; set; }
        public string WorkState { get; set; }
        public int WorkStateSource { get; set; }
        public string WorkersCompensationCode { get; set; }
        public string WorkersCompensationState { get; set; }
    }
}